slam_toolbox:
  ros__parameters:
    use_sim_time: false
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping # (mapping / localization)
    map_update_interval: 2.0
    transform_publish_period: 0.02
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.05
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    enable_interactive_mode: false
