twist_mux:
  ros__parameters:
    use_stamped: true
    topics:
      joystick:
        topic   : /input_joy/cmd_vel_stamped
        timeout : 0.5
        priority: 100
      keyboard: 
        topic   : /input_key/cmd_vel_stamped
        timeout : 0.5
        priority: 90
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 80